require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DispensalsController do

  # This should return the minimal set of attributes required to create a valid
  # Dispensal. As you add validations to Dispensal, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DispensalsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dispensals as @dispensals" do
      dispensal = Dispensal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dispensals).should eq([dispensal])
    end
  end

  describe "GET show" do
    it "assigns the requested dispensal as @dispensal" do
      dispensal = Dispensal.create! valid_attributes
      get :show, {:id => dispensal.to_param}, valid_session
      assigns(:dispensal).should eq(dispensal)
    end
  end

  describe "GET new" do
    it "assigns a new dispensal as @dispensal" do
      get :new, {}, valid_session
      assigns(:dispensal).should be_a_new(Dispensal)
    end
  end

  describe "GET edit" do
    it "assigns the requested dispensal as @dispensal" do
      dispensal = Dispensal.create! valid_attributes
      get :edit, {:id => dispensal.to_param}, valid_session
      assigns(:dispensal).should eq(dispensal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dispensal" do
        expect {
          post :create, {:dispensal => valid_attributes}, valid_session
        }.to change(Dispensal, :count).by(1)
      end

      it "assigns a newly created dispensal as @dispensal" do
        post :create, {:dispensal => valid_attributes}, valid_session
        assigns(:dispensal).should be_a(Dispensal)
        assigns(:dispensal).should be_persisted
      end

      it "redirects to the created dispensal" do
        post :create, {:dispensal => valid_attributes}, valid_session
        response.should redirect_to(Dispensal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dispensal as @dispensal" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dispensal.any_instance.stub(:save).and_return(false)
        post :create, {:dispensal => {}}, valid_session
        assigns(:dispensal).should be_a_new(Dispensal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dispensal.any_instance.stub(:save).and_return(false)
        post :create, {:dispensal => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dispensal" do
        dispensal = Dispensal.create! valid_attributes
        # Assuming there are no other dispensals in the database, this
        # specifies that the Dispensal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dispensal.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dispensal.to_param, :dispensal => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dispensal as @dispensal" do
        dispensal = Dispensal.create! valid_attributes
        put :update, {:id => dispensal.to_param, :dispensal => valid_attributes}, valid_session
        assigns(:dispensal).should eq(dispensal)
      end

      it "redirects to the dispensal" do
        dispensal = Dispensal.create! valid_attributes
        put :update, {:id => dispensal.to_param, :dispensal => valid_attributes}, valid_session
        response.should redirect_to(dispensal)
      end
    end

    describe "with invalid params" do
      it "assigns the dispensal as @dispensal" do
        dispensal = Dispensal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dispensal.any_instance.stub(:save).and_return(false)
        put :update, {:id => dispensal.to_param, :dispensal => {}}, valid_session
        assigns(:dispensal).should eq(dispensal)
      end

      it "re-renders the 'edit' template" do
        dispensal = Dispensal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dispensal.any_instance.stub(:save).and_return(false)
        put :update, {:id => dispensal.to_param, :dispensal => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dispensal" do
      dispensal = Dispensal.create! valid_attributes
      expect {
        delete :destroy, {:id => dispensal.to_param}, valid_session
      }.to change(Dispensal, :count).by(-1)
    end

    it "redirects to the dispensals list" do
      dispensal = Dispensal.create! valid_attributes
      delete :destroy, {:id => dispensal.to_param}, valid_session
      response.should redirect_to(dispensals_url)
    end
  end

end
