require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FarmersController do

  # This should return the minimal set of attributes required to create a valid
  # Farmer. As you add validations to Farmer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FarmersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all farmers as @farmers" do
      farmer = Farmer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:farmers).should eq([farmer])
    end
  end

  describe "GET show" do
    it "assigns the requested farmer as @farmer" do
      farmer = Farmer.create! valid_attributes
      get :show, {:id => farmer.to_param}, valid_session
      assigns(:farmer).should eq(farmer)
    end
  end

  describe "GET new" do
    it "assigns a new farmer as @farmer" do
      get :new, {}, valid_session
      assigns(:farmer).should be_a_new(Farmer)
    end
  end

  describe "GET edit" do
    it "assigns the requested farmer as @farmer" do
      farmer = Farmer.create! valid_attributes
      get :edit, {:id => farmer.to_param}, valid_session
      assigns(:farmer).should eq(farmer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Farmer" do
        expect {
          post :create, {:farmer => valid_attributes}, valid_session
        }.to change(Farmer, :count).by(1)
      end

      it "assigns a newly created farmer as @farmer" do
        post :create, {:farmer => valid_attributes}, valid_session
        assigns(:farmer).should be_a(Farmer)
        assigns(:farmer).should be_persisted
      end

      it "redirects to the created farmer" do
        post :create, {:farmer => valid_attributes}, valid_session
        response.should redirect_to(Farmer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved farmer as @farmer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Farmer.any_instance.stub(:save).and_return(false)
        post :create, {:farmer => {}}, valid_session
        assigns(:farmer).should be_a_new(Farmer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Farmer.any_instance.stub(:save).and_return(false)
        post :create, {:farmer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested farmer" do
        farmer = Farmer.create! valid_attributes
        # Assuming there are no other farmers in the database, this
        # specifies that the Farmer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Farmer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => farmer.to_param, :farmer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested farmer as @farmer" do
        farmer = Farmer.create! valid_attributes
        put :update, {:id => farmer.to_param, :farmer => valid_attributes}, valid_session
        assigns(:farmer).should eq(farmer)
      end

      it "redirects to the farmer" do
        farmer = Farmer.create! valid_attributes
        put :update, {:id => farmer.to_param, :farmer => valid_attributes}, valid_session
        response.should redirect_to(farmer)
      end
    end

    describe "with invalid params" do
      it "assigns the farmer as @farmer" do
        farmer = Farmer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Farmer.any_instance.stub(:save).and_return(false)
        put :update, {:id => farmer.to_param, :farmer => {}}, valid_session
        assigns(:farmer).should eq(farmer)
      end

      it "re-renders the 'edit' template" do
        farmer = Farmer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Farmer.any_instance.stub(:save).and_return(false)
        put :update, {:id => farmer.to_param, :farmer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested farmer" do
      farmer = Farmer.create! valid_attributes
      expect {
        delete :destroy, {:id => farmer.to_param}, valid_session
      }.to change(Farmer, :count).by(-1)
    end

    it "redirects to the farmers list" do
      farmer = Farmer.create! valid_attributes
      delete :destroy, {:id => farmer.to_param}, valid_session
      response.should redirect_to(farmers_url)
    end
  end

end
